baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Home'
theme = 'minimo'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[services]
  [services.disqus]
    shortname = 'johansivertsen'

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about", "sidebar_menu"]
footer = ["social_menu"]